### ISSUE TITLE
Admin Dashboard timeout after enabling the graph

### ISSUE THREAD

**Issue by farahats9** [PetrDlouhy/django-admin-charts#16]
I am getting a timeout when I make the graph visible and go back to the dashboard. the issue is not happening on my development machine which runs windows. It only happens on the server running ubuntu 18.04 with Nginx. No errors show up in the logs. the machine is decent and the graph  is not supposed to be querying much data (only users model which have 2 users)

Any advice on how to debug this issue?
Edit: I noticed on my development machine I get this exception but the page loads without issues
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63565)
Traceback (most recent call last):
  File "c:\users\farah\appdata\local\programs\python\python37\Lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\farah\appdata\local\programs\python\python37\Lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\farah\appdata\local\programs\python\python37\Lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\dev\python\bestevdeals\.venv\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\dev\python\bestevdeals\.venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\farah\appdata\local\programs\python\python37\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
```

**Comment by PetrDlouhy** [comment]
@farahats9 I am afraid, I cannot help much here. I don't see much info related to `django-admin-charts` here.
What is the request URL (endpoint) on which this timeout happens? What is your timeout settings (Django itself doesn't have timeout, it usually is set on WSGI server, e.g. Gunicorn or Nginx)? How long does the request run?

**Comment by PetrDlouhy** [comment]
I am closing this. @farahats9 If the error is still present, please post more info and reopen.
