### ISSUE TITLE
TypeError: Object of type Decimal is not JSON serializable

### ISSUE THREAD

**Issue by WhiteRose7-pretty** [PetrDlouhy/django-admin-charts#26]
Hello, @PetrDlouhy 
I have created dashboard stat object with bottom parameters.
![image](https://user-images.githubusercontent.com/53968816/97202481-a6060600-17ee-11eb-9932-c75ad2ee82db.png)
There are data like bottom.
![image](https://user-images.githubusercontent.com/53968816/97147489-8fd35800-17a4-11eb-8bde-b00388bef62f.png)
Model is ,
```
class TransactionHistory(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    type = models.CharField(default='subscription', max_length=20)  # subsription and advertise
    twispay_id = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
```
but I am getting this error.
  File "C:\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable

Thank you for your help with previous issue.

**Comment by PetrDlouhy** [comment]
Hi @WhiteRose7-pretty,

Please write what exactly you mean by "I can't draw chart'.

I see one mistake in values that you set - you would probably want to set `Sum` instead of `Count` in `Choose type operation`. But I think that even this setting should draw something.

**Comment by WhiteRose7-pretty** [comment]
Hello @PetrDlouhy  I have changed count -> Sum, But I am getting above error,
I have updated title and content, Please check again.

**Comment by WhiteRose7-pretty** [comment]
Hello @PetrDlouhy I found that decimal field is making bug, So I changed to Integerfield, I used "sum" instead of count, but I am getting sum of number of objects, I want to get sum of amount field,

**Comment by PetrDlouhy** [comment]
The error in original description could be caused by JsonField in Dashboard criteria. Did you use that?
I don't see where from `django-admin-charts` code it is the traceback thrown from. Is that the whole traceback?

The DecimalField shouldn't be problem - I use that on several places with Sum.

**Comment by WhiteRose7-pretty** [comment]
I haven't used Dashboard criteria yet, 
I have changed django version from 3.0 to 2.2.
it work in 2.2, but DecimalField is not working yet.

**Comment by PetrDlouhy** [comment]
I am using Django 3.0
Without the whole traceback I really don't know what is going on.

**Comment by WhiteRose7-pretty** [comment]
```
HTTP GET /admin_tools_stats/chart_data/type_user_register/?csrfmiddlewaretoken=nJdbdZF5uX8g57wmaDIavrsbBMSvXT4T3XZBYOSr5jreuWQXvrMt9NlpABCCOVBi&select_box_dynamic_5=&graph_key=type_user_register&select_box_interval=days&time_since=2020-09-27&time_until=2020-10-27&s
elect_box_chart_type=multiBarChart&_=1603790927781 200 [0.17, 127.0.0.1:57927]
Internal Server Error: /admin_tools_stats/chart_data/transaction_history/
Traceback (most recent call last):
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django_nvd3\templatetags\nvd3_tags.py", line 72, in load_chart
    chart.buildcontent()
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\nvd3\NVD3Chart.py", line 484, in buildcontent
    self.buildjschart()
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\nvd3\NVD3Chart.py", line 417, in buildjschart
    self.series_js = json.dumps(self.series)
  File "C:\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable

```
Hello @PetrDlouhy  I writed whole traceback.

**Comment by PetrDlouhy** [comment]
That seems like some problem with `python_nvd3`/`django_nvd3`. What versions do you have installed?

**Comment by WhiteRose7-pretty** [comment]
I am using django-nvd3 ==0.9.7 .

**Comment by PetrDlouhy** [comment]
Same version here. But I found out what might be the problem. Your configuration doesn't allow to serialize the `Decimal` to JSON. Probably you don't have `simplejson` installed or do have old version. My version is `3.17.2`.

**Comment by WhiteRose7-pretty** [comment]
yes, I don't have simplejson, so I installed simplejson 3.17.2. but same bug
 ```
 File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\django_nvd3\templatetags\nvd3_tags.py", line 72, in load_chart
    chart.buildcontent()
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\nvd3\NVD3Chart.py", line 478, in buildcontent
    self.buildjschart()
  File "F:\Python\Django\Auriala\Auriala\hvenv\lib\site-packages\nvd3\NVD3Chart.py", line 412, in buildjschart
    self.series_js = json.dumps(self.series)
  File "C:\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable


```

**Comment by WhiteRose7-pretty** [comment]
I am using python-nvd3 == 0.13.7.

**Comment by PetrDlouhy** [comment]
@WhiteRose7-pretty Did the installation of `simplejson` solve the problem? Was there anything else, that you had to do?

I would like update the documentation with some info about DecimalFields

**Comment by WhiteRose7-pretty** [comment]
yes, I have installed simplejson only,
but in my side, it is working in Django 2.2 only.

**Comment by PetrDlouhy** [comment]
@WhiteRose7-pretty I have added small note to the requirements section in readme.

Could you please take a look at the whole documentation if there is something to improve what would help you to get `django-admin-charts` working?

**Comment by WhiteRose7-pretty** [comment]
I am sorry I missed your message, I have looked your document, Package and document are excellent. Thank you.
