### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by Simouche** [PetrDlouhy/django-admin-charts#29]
I'm using django 3.1, I installed django-admin-tools 0.9.1 and wanted to add django-admin-charts 0.24.1.
but whenever i try to run `py manage.py check` it throws `AttributeError: 'NoneType' object has no attribute 'rsplit'`.
any help about this?

**Comment by PetrDlouhy** [comment]
Hi @Simouche,

I don't know about that, I am using Django 3.1 just fine. Could you please send the whole traceback?

**Comment by Simouche** [comment]
Hey @PetrDlouhy , thanks for the fast reply, yeah here is the traceback:
```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\admin_tools_stats\models.py", line 535, in <module>
    class CriteriaToStatsM2M(models.Model):
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\admin_tools_stats\models.py", line 599, in CriteriaToStatsM2M
    @cached(60 * 5)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\cache_utils\decorators.py", line 46, in cached
    cache_backend = caches['default']
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\core\cache\__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\core\cache\__init__.py", line 50, in _create_cache
    backend_cls = import_string(backend)
  File "C:\Users\pc\Desktop\Work\Freelance\Ecommerce\venv\lib\site-packages\django\utils\module_loading.py", line 13, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

**Comment by PetrDlouhy** [comment]
@Simouche Do you have set up the `default` cache? With something like this: https://docs.djangoproject.com/en/3.2/topics/cache/#memcached
It might be missing in the README, so if it is that case, I will put it there.

**Comment by Simouche** [comment]
yeah that was the case, i had:
```
CACHES = {
     'default': {
         'BACKEND': None,
     }
 }
```
and since i don't use any cachine (right now), i removed that, and it's working.
i'd suggest you point that out (that the caching backend shouldn't be None).

**Comment by PetrDlouhy** [comment]
@Simouche The `django-admin-charts` uses caching to speed up certain operations. So without working cache you can have slower charts.
