### ISSUE TITLE
Trouble with dependencies using Django 4

### ISSUE THREAD

**Issue by johnmathews** [PetrDlouhy/django-admin-charts#41]
To be fair, I don't know much about pip, or eggs. 
My app runs `django4.0.2` and I've added the following requirements:

```
git+https://github.com/PetrDlouhy/django-cache-utils@django40#djcacheutils
django-admin-charts==1.0.0  # https://github.com/PetrDlouhy/django-admin-charts
```

pip errors during install with the following error message:
```
Collecting python-nvd3==0.14.2
  Using cached python-nvd3-0.14.2.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of django-nvd3 to determine which version is compatible with other requirements. This could take a while.
Collecting django-nvd3>=0.5.0
  Using cached django-nvd3-0.9.6.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
  Using cached django-nvd3-0.9.5.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting python-nvd3==0.14.1
  Using cached python-nvd3-0.14.1.tar.gz (30 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/fh/znj37m116kg4jwsckd1rr4q40000gn/T/pip-install-o5yo7dpd/python-nvd3_4a531dad6e6e44afa77f0e0a417d4f4b/setup.py", line 13, in <module>
          with open('CHANGELOG.rst') as history_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
      [end of output]

```
Do you have any advice how to run `django-admin-charts` on `Django 4`?

**Comment by PetrDlouhy** [comment]
The error comes from `python-nvd3`. When I tried to install version `0.14.2` everything goes fine, but when I tried version `0.14.1` the `No such file or directory: 'CHANGELOG.rst'` error raises.

But I am not sure, why your installation falls for `0.14.1`.

**Comment by johnmathews** [comment]
Thank you. That fixed it.
